/* Generated by backend/scripts/build-catalog.mjs. Edit shop/**-data.js instead. */

export const PRODUCTS = [
    {
        "id": "shirt1",
        "title": "doodler",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "black",
                "label": "black"
            },
            {
                "id": "pink",
                "label": "pink"
            },
            {
                "id": "red",
                "label": "red"
            },
            {
                "id": "blue",
                "label": "blue"
            },
            {
                "id": "brown",
                "label": "brown"
            },
            {
                "id": "green",
                "label": "green"
            },
            {
                "id": "dark-green",
                "label": "dark green"
            },
            {
                "id": "washed-green",
                "label": "washed green"
            },
            {
                "id": "purple",
                "label": "purple"
            },
            {
                "id": "dark-purple",
                "label": "dark purple"
            },
            {
                "id": "dark-blue",
                "label": "dark blue"
            },
            {
                "id": "grey",
                "label": "grey"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00001.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00001.png"
            },
            "black::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler000025.png"
            },
            "black::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler000011.png"
            },
            "pink::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00019.png"
            },
            "pink::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00003.png"
            },
            "red::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00021.png"
            },
            "red::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00009.png"
            },
            "blue::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00023.png"
            },
            "blue::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00005.png"
            },
            "brown::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00007.png"
            },
            "brown::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00007.png"
            },
            "green::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00017.png"
            },
            "dark-green::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00015.png"
            },
            "washed-green::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00003.png"
            },
            "purple::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00005.png"
            },
            "dark-purple::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00013.png"
            },
            "dark-blue::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00011.png"
            },
            "grey::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00009.png"
            }
        }
    },
    {
        "id": "shirt2",
        "title": "poser",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "pink",
                "label": "pink"
            },
            {
                "id": "blue",
                "label": "blue"
            },
            {
                "id": "red",
                "label": "red"
            },
            {
                "id": "brown",
                "label": "brown"
            },
            {
                "id": "purple",
                "label": "purple"
            },
            {
                "id": "dark-purple",
                "label": "dark purple"
            },
            {
                "id": "dark-blue",
                "label": "dark blue"
            },
            {
                "id": "grey",
                "label": "grey"
            },
            {
                "id": "dark-grey",
                "label": "dark grey"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00001.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00001.png"
            },
            "pink::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00003.png"
            },
            "pink::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00003.png"
            },
            "blue::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00013.png"
            },
            "blue::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00005.png"
            },
            "red::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00007.png"
            },
            "red::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00007.png"
            },
            "brown::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00009.png"
            },
            "brown::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00009.png"
            },
            "purple::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00011.png"
            },
            "dark-purple::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00015.png"
            },
            "dark-blue::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00017.png"
            },
            "grey::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00019.png"
            },
            "dark-grey::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00021.png"
            }
        }
    },
    {
        "id": "shirt3",
        "title": "adrien brody",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "pink",
                "label": "pink"
            },
            {
                "id": "grey",
                "label": "grey"
            },
            {
                "id": "blue",
                "label": "blue"
            },
            {
                "id": "orange",
                "label": "orange"
            },
            {
                "id": "green",
                "label": "green"
            },
            {
                "id": "black",
                "label": "black"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00001.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/adrien brody/EC_adrienbrody00001.png"
            },
            "pink::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00003.png"
            },
            "pink::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/adrien brody/EC_adrienbrody00003.png"
            },
            "grey::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00005.png"
            },
            "blue::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/adrien brody/EC_adrienbrody00005.png"
            },
            "orange::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00007.png"
            },
            "green::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00009.png"
            },
            "black::snow-washed": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00011.png"
            },
            "black::essential-cotton": {
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/adrien brody/EC_adrienbrody00007.png"
            }
        }
    },
    {
        "id": "shirt4",
        "title": "stork",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "pink",
                "label": "pink"
            },
            {
                "id": "green",
                "label": "green"
            },
            {
                "id": "purple",
                "label": "purple"
            },
            {
                "id": "red",
                "label": "red"
            },
            {
                "id": "blue",
                "label": "blue"
            },
            {
                "id": "brown",
                "label": "brown"
            },
            {
                "id": "dark-brown",
                "label": "dark brown"
            },
            {
                "id": "washed-green",
                "label": "washed green"
            },
            {
                "id": "dark-grey",
                "label": "dark grey"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00001.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/storks/EC_stork00001.png"
            },
            "pink::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00007.png"
            },
            "pink::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/storks/EC_stork00003.png"
            },
            "green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00005.png"
            },
            "purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00003.png"
            },
            "red::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00009.png"
            },
            "blue::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00011.png"
            },
            "blue::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/storks/EC_stork00005.png"
            },
            "brown::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00017.png"
            },
            "dark-brown::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00021.png"
            },
            "dark-brown::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/storks/EC_stork00007.png"
            },
            "washed-green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00015.png"
            },
            "dark-grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00019.png"
            }
        }
    },
    {
        "id": "shirt5",
        "title": "purple people eater",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "black",
                "label": "black"
            },
            {
                "id": "grey",
                "label": "grey"
            },
            {
                "id": "green",
                "label": "green"
            },
            {
                "id": "dark-brown",
                "label": "dark brown"
            },
            {
                "id": "blue",
                "label": "blue"
            },
            {
                "id": "purple",
                "label": "purple"
            },
            {
                "id": "dark-purple",
                "label": "dark purple"
            },
            {
                "id": "pink",
                "label": "pink"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00003.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00003.png"
            },
            "black::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00001.png"
            },
            "black::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00001.png"
            },
            "grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00005.png"
            },
            "green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00007.png"
            },
            "dark-brown::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00009.png"
            },
            "dark-brown::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00009.png"
            },
            "blue::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00011.png"
            },
            "blue::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00007.png"
            },
            "purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00015.png"
            },
            "dark-purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00013.png"
            },
            "pink::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00005.png"
            }
        }
    },
    {
        "id": "shirt6",
        "title": "house",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "red",
                "label": "red"
            },
            {
                "id": "green",
                "label": "green"
            },
            {
                "id": "purple",
                "label": "purple"
            },
            {
                "id": "grey",
                "label": "grey"
            },
            {
                "id": "pink",
                "label": "pink"
            },
            {
                "id": "blue",
                "label": "blue"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00001.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/house1/EC_house1_00001.png"
            },
            "red::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00003.png"
            },
            "green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00005.png"
            },
            "purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00007.png"
            },
            "grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00009.png"
            },
            "pink::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00011.png"
            },
            "pink::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/house1/EC_house1_00003.png"
            },
            "blue::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00013.png"
            },
            "blue::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/house1/EC_house1_00005.png"
            }
        }
    },
    {
        "id": "shirt7",
        "title": "squiggles",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /squiggles/SW_squiggles00001.png"
            },
            "::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/squiggles/EC_squiggles00001.png"
            }
        }
    },
    {
        "id": "shirt8",
        "title": "circus lion",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "grey",
                "label": "grey"
            },
            {
                "id": "brown",
                "label": "brown"
            },
            {
                "id": "blue",
                "label": "blue"
            },
            {
                "id": "green",
                "label": "green"
            },
            {
                "id": "pink",
                "label": "pink"
            },
            {
                "id": "purple",
                "label": "purple"
            },
            {
                "id": "dark-grey",
                "label": "dark grey"
            },
            {
                "id": "dark-blue",
                "label": "dark blue"
            },
            {
                "id": "dark-brown",
                "label": "dark brown"
            },
            {
                "id": "washed-green",
                "label": "washed green"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00001.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c lion/EC_clion00001.png"
            },
            "grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00003.png"
            },
            "brown::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00015.png"
            },
            "blue::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00007.png"
            },
            "blue::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c lion/EC_clion00005.png"
            },
            "green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00011.png"
            },
            "pink::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00013.png"
            },
            "pink::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c lion/EC_clion00003.png"
            },
            "purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00019.png"
            },
            "dark-grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00017.png"
            },
            "dark-blue::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00021.png"
            },
            "dark-brown::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00005.png"
            },
            "dark-brown::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c lion/EC_clion00007.png"
            },
            "washed-green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00009.png"
            }
        }
    },
    {
        "id": "shirt9",
        "title": "circus crocodile",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "green",
                "label": "green"
            },
            {
                "id": "pink",
                "label": "pink"
            },
            {
                "id": "grey",
                "label": "grey"
            },
            {
                "id": "dark-grey",
                "label": "dark grey"
            },
            {
                "id": "purple",
                "label": "purple"
            },
            {
                "id": "dark-blue",
                "label": "dark blue"
            },
            {
                "id": "blue",
                "label": "blue"
            },
            {
                "id": "dark-brown",
                "label": "dark brown"
            },
            {
                "id": "washed-green",
                "label": "washed green"
            },
            {
                "id": "washed-purple",
                "label": "washed purple"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00001.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c croc/EC_ccroc00001.png"
            },
            "green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00015.png"
            },
            "pink::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00019.png"
            },
            "pink::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c croc/EC_ccroc00003.png"
            },
            "grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00009.png"
            },
            "dark-grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00017.png"
            },
            "purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00013.png"
            },
            "dark-blue::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00011.png"
            },
            "blue::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c croc/EC_ccroc00005.png"
            },
            "dark-brown::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00007.png"
            },
            "dark-brown::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c croc/EC_ccroc00007.png"
            },
            "washed-green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00003.png"
            },
            "washed-purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00005.png"
            }
        }
    },
    {
        "id": "shirt10",
        "title": "circus elephant",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "pink",
                "label": "pink"
            },
            {
                "id": "grey",
                "label": "grey"
            },
            {
                "id": "blue",
                "label": "blue"
            },
            {
                "id": "purple",
                "label": "purple"
            },
            {
                "id": "dark-blue",
                "label": "dark blue"
            },
            {
                "id": "green",
                "label": "green"
            },
            {
                "id": "dark-brown",
                "label": "dark brown"
            },
            {
                "id": "washed-green",
                "label": "washed green"
            },
            {
                "id": "dark-grey",
                "label": "dark grey"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00002.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c elephant/EC_celephant00001.png"
            },
            "pink::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00018.png"
            },
            "pink::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c elephant/EC_celephant00005.png"
            },
            "grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00004.png"
            },
            "blue::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c elephant/EC_celephant00007.png"
            },
            "purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00008.png"
            },
            "dark-blue::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00006.png"
            },
            "green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00016.png"
            },
            "dark-brown::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00012.png"
            },
            "dark-brown::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c elephant/EC_celephant00003.png"
            },
            "washed-green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00014.png"
            },
            "dark-grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00010.png"
            }
        }
    },
    {
        "id": "shirt11",
        "title": "circus monkey",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "pink",
                "label": "pink"
            },
            {
                "id": "green",
                "label": "green"
            },
            {
                "id": "washed-green",
                "label": "washed green"
            },
            {
                "id": "washed-purple",
                "label": "washed purple"
            },
            {
                "id": "dark-blue",
                "label": "dark blue"
            },
            {
                "id": "purple",
                "label": "purple"
            },
            {
                "id": "dark-grey",
                "label": "dark grey"
            },
            {
                "id": "brown",
                "label": "brown"
            },
            {
                "id": "dark-brown",
                "label": "dark brown"
            },
            {
                "id": "grey",
                "label": "grey"
            },
            {
                "id": "blue",
                "label": "blue"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00001.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c monkey/EC_cmonkey00001.png"
            },
            "pink::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00003.png"
            },
            "pink::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c monkey/EC_cmonkey00003.png"
            },
            "green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00005.png"
            },
            "washed-green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00007.png"
            },
            "washed-purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00009.png"
            },
            "dark-blue::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00011.png"
            },
            "purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00013.png"
            },
            "dark-grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00015.png"
            },
            "brown::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00017.png"
            },
            "dark-brown::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00023.png"
            },
            "dark-brown::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c monkey/EC_cmonkey00007.png"
            },
            "grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00019.png"
            },
            "blue::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00021.png"
            },
            "blue::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c monkey/EC_cmonkey00005.png"
            }
        }
    },
    {
        "id": "shirt12",
        "title": "circus bunny",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "pink",
                "label": "pink"
            },
            {
                "id": "green",
                "label": "green"
            },
            {
                "id": "washed-green",
                "label": "washed green"
            },
            {
                "id": "washed-purple",
                "label": "washed purple"
            },
            {
                "id": "purple",
                "label": "purple"
            },
            {
                "id": "dark-grey",
                "label": "dark grey"
            },
            {
                "id": "dark-brown",
                "label": "dark brown"
            },
            {
                "id": "grey",
                "label": "grey"
            },
            {
                "id": "blue",
                "label": "blue"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00001.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c bunny/EC_cbunny00001.png"
            },
            "pink::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00009.png"
            },
            "pink::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c bunny/EC_cbunny00003.png"
            },
            "green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00015.png"
            },
            "washed-green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00003.png"
            },
            "washed-purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00005.png"
            },
            "purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00013.png"
            },
            "dark-grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00019.png"
            },
            "dark-brown::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00017.png"
            },
            "dark-brown::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c bunny/EC_cbunny00007.png"
            },
            "grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00011.png"
            },
            "blue::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00007.png"
            },
            "blue::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c bunny/EC_cbunny00005.png"
            }
        }
    },
    {
        "id": "shirt13",
        "title": "circus ensemble",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "pink",
                "label": "pink"
            },
            {
                "id": "green",
                "label": "green"
            },
            {
                "id": "brown",
                "label": "brown"
            },
            {
                "id": "washed-green",
                "label": "washed green"
            },
            {
                "id": "purple",
                "label": "purple"
            },
            {
                "id": "dark-brown",
                "label": "dark brown"
            },
            {
                "id": "grey",
                "label": "grey"
            },
            {
                "id": "blue",
                "label": "blue"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00001.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid/EC_cgrid00001.png"
            },
            "pink::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid/EC_cgrid00003.png"
            },
            "green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00007.png"
            },
            "brown::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00009.png"
            },
            "washed-green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00003.png"
            },
            "purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00013.png"
            },
            "dark-brown::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid/EC_cgrid00007.png"
            },
            "grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00005.png"
            },
            "blue::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00011.png"
            },
            "blue::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid/EC_cgrid00005.png"
            }
        }
    },
    {
        "id": "shirt14",
        "title": "circus outlines",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "purple",
                "label": "purple"
            },
            {
                "id": "green",
                "label": "green"
            },
            {
                "id": "pink",
                "label": "pink"
            },
            {
                "id": "blue",
                "label": "blue"
            },
            {
                "id": "dark-brown",
                "label": "dark brown"
            },
            {
                "id": "washed-grey",
                "label": "washed grey"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00001.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid outline/EC_cgridoutline00001.png"
            },
            "purple::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00003.png"
            },
            "green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00005.png"
            },
            "pink::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00007.png"
            },
            "pink::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid outline/EC_cgridoutline00007.png"
            },
            "blue::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00009.png"
            },
            "blue::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid outline/EC_cgridoutline00005.png"
            },
            "dark-brown::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid outline/EC_cgridoutline00002.png"
            },
            "washed-grey::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00011.png"
            }
        }
    },
    {
        "id": "shirt15",
        "title": "the essential burger",
        "category": "shirts",
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "colors": [
            {
                "id": "snow",
                "label": "snow"
            },
            {
                "id": "red",
                "label": "red"
            },
            {
                "id": "dark-green",
                "label": "dark green"
            },
            {
                "id": "green",
                "label": "green"
            }
        ],
        "materials": [
            {
                "id": "snow-washed",
                "label": "oversized snow washed"
            },
            {
                "id": "essential-cotton",
                "label": "essential cotton"
            }
        ],
        "defaultColorId": "snow",
        "defaultMaterialId": "snow-washed",
        "variants": {
            "snow::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00001.png"
            },
            "snow::essential-cotton": {
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/hamburger/EC_hamburger00001.png"
            },
            "red::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00005.png"
            },
            "dark-green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00003.png"
            },
            "green::snow-washed": {
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00007.png"
            }
        }
    },
    {
        "id": "print1",
        "title": "Cyanotype",
        "category": "prints",
        "sizes": [],
        "colors": [],
        "materials": [],
        "defaultColorId": "",
        "defaultMaterialId": "",
        "variants": {
            "::": {
                "priceCents": 1500,
                "imagePath": "/assets/GalleryAssets/visual-art/ArtPiece.png"
            }
        }
    },
    {
        "id": "print2",
        "title": "Linoprint",
        "category": "prints",
        "sizes": [],
        "colors": [],
        "materials": [],
        "defaultColorId": "",
        "defaultMaterialId": "",
        "variants": {
            "::": {
                "priceCents": 1500,
                "imagePath": ""
            }
        }
    },
    {
        "id": "Digital Print",
        "title": "Print 3",
        "category": "prints",
        "sizes": [],
        "colors": [],
        "materials": [],
        "defaultColorId": "",
        "defaultMaterialId": "",
        "variants": {
            "::": {
                "priceCents": 1500,
                "imagePath": ""
            }
        }
    },
    {
        "id": "more1",
        "title": "bbb",
        "category": "more",
        "sizes": [],
        "colors": [],
        "materials": [],
        "defaultColorId": "",
        "defaultMaterialId": "",
        "variants": {
            "::": {
                "priceCents": 1000,
                "imagePath": "/assets/images/Package.png"
            }
        }
    },
    {
        "id": "more2",
        "title": "aaa",
        "category": "more",
        "sizes": [],
        "colors": [],
        "materials": [],
        "defaultColorId": "",
        "defaultMaterialId": "",
        "variants": {
            "::": {
                "priceCents": 1000,
                "imagePath": ""
            }
        }
    },
    {
        "id": "more3",
        "title": "More 3",
        "category": "more",
        "sizes": [],
        "colors": [],
        "materials": [],
        "defaultColorId": "",
        "defaultMaterialId": "",
        "variants": {
            "::": {
                "priceCents": 1000,
                "imagePath": ""
            }
        }
    }
];
